//statefulset-definition.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            -   name: mysql
                image: mysql
    replicas:3
    selector:
        matchLabels:
            app: mysql
    serviceName: mysql-h
    
##kubectl create -f statefulset-definition.yml
## Ordered graceful deployment

kubectl scale statefulset mysql --replicas=5


kubectl scale statefulset mysql --replicas=3

kubectl delete statefulset mysql
## delete will delete pods from last one. last one will be deleted first. (reverse order)
