 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  template:
    metadata:
      name: httpd-pod
      labels:
        name: httpd
        type: webserver
    spec:
      containers:
        - name: httpd-alpine
          image: httpd:2.4-alpine
  selector:
    matchLabels:
      name: httpd
  replicas: 3
...
