apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  clusterIP: 10.43.235.125
  clusterIPs:
  - 10.43.235.125
  ports:
  - nodePort: 30082
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: blue
  sessionAffinity: None
  type: NodePort
