apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - nodePort: 30612
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: NodePort
